groups:
  - name: app1
    rules:
      - alert: "During the last minute more than one ExceptionWhileObserved has been thrown"
        expr: increase({__name__=~"[^(http)].*count",error="ExceptionWhileObserved"}[1m]) > 0
        for: 10s
        labels:
          severity: warning
          value: '{{ $value }}'
        annotations:
          summary: "ExceptionWhileObserved has been thrown more than once in the last minute. See https://confluence.organization.com/monitoring/alerts/ExceptionWhileObserved for more information"
  - name: app2
    rules:
      - alert: Ssl exception occured
        expr: increase(last_ssl_exception_timestamp[10m]) > 0
        for: 5s
        labels:
          severity: page
          value: '{{ $value }}'
        annotations:
          summary: "PAASUKE_SSL_EXCEPTION_OCCURED - Some application(s) have encountered certificate/ssl related errors"
